<div id='g-Index-Page-Design-box' class='ai2html'>
    <!-- Generated by ai2html v0.64 - 2017-06-21 - 22:16 -->
    <!-- ai file: Index-Page-Design -->

    <style type='text/css' media='screen,print'>
        .g-artboard {
            margin:0 auto;
        }
    </style>


    <!-- Artboard: Artboard_1_copy_2 -->
    <div id='g-Index-Page-Design-Artboard_1_copy_2' class='g-artboard g-artboard-v3 ' data-min-width='800'>
        <style type='text/css' media='screen,print'>
            #g-Index-Page-Design-Artboard_1_copy_2{
                position:relative;
                overflow:hidden;
                width:800px;
            }
            .g-aiAbs{
                position:absolute;
            }
            .g-aiImg{
                display:block;
                width:100% !important;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 p{
                font-family:nyt-franklin,arial,helvetica,sans-serif;
                font-size:13px;
                line-height:18px;
                margin:0;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle0 {
                font-size:34px;
                line-height:36px;
                text-align:center;
                color:#ffffff;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle1 {
                font-size:30px;
                line-height:40px;
                text-align:center;
                color:#f1592a;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle2 {
                font-size:27px;
                line-height:35px;
                text-align:center;
                color:#353535;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle3 {
                font-size:4px;
                line-height:6px;
                color:#000000;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle4 {
                font-size:27px;
                line-height:35px;
                text-align:center;
                color:#f1582c;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle5 {
                font-size:20px;
                line-height:40px;
                text-align:center;
                letter-spacing:0.09166666666667em;
                color:#ffffff;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle6 {
                font-size:18px;
                line-height:27px;
                text-align:center;
                color:#ffffff;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle7 {
                font-size:5px;
                line-height:8px;
                text-align:center;
                color:#ffffff;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle8 {
                font-size:6px;
                line-height:7px;
                color:#ff5721;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle9 {
                font-size:15px;
                line-height:22px;
                text-align:center;
                color:#ffffff;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle10 {
                font-size:20px;
                line-height:39px;
                text-align:center;
                color:#fff200;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle11 {
                font-size:27px;
                line-height:35px;
                text-align:center;
                color:#353535;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle12 {
                font-size:27px;
                line-height:40px;
                text-align:center;
                color:#353535;
            }
            #g-Index-Page-Design-Artboard_1_copy_2 .g-aiPstyle13 {
                font-size:28px;
                line-height:54px;
                text-align:center;
                letter-spacing:0.09166666666667em;
                color:#ff5722;
            }
            .g-aiPtransformed p { white-space: nowrap; }
        </style>
        <div id='g-Index-Page-Design-Artboard_1_copy_2-graphic'>
            <img id='g-ai0-0'
                 class='g-aiImg'
                 src='Index-Page-Design-Artboard_1_copy_2.png'
                 />
            <div id='g-ai0-1' class='g-Layer_4 g-aiAbs' style='top:0.7557%;left:88.4174%;width:19.8818%;margin-left:-9.9409%;'>
                <p class='g-aiPstyle0'>FITUR</p>
                <p class='g-aiPstyle0'>BARU</p>
            </div>
            <div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:17.0175%;left:50%;width:112.7085%;margin-left:-56.3542%;'>
                <p class='g-aiPstyle1'>APA ITU PENJUAL TERPILIH SHOPEE?</p>
            </div>
            <div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:18.4449%;left:50%;width:87.5%;margin-left:-43.75%;'>
                <p class='g-aiPstyle2'>Sebuah apresiasi untuk penjual yang aktif dan</p>
                <p class='g-aiPstyle2'>memiliki pelayanan pelanggan yang baik </p>
            </div>
            <div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:22.1115%;left:50%;width:112.8887%;margin-left:-56.4443%;'>
                <p class='g-aiPstyle1'>KRITERIA PENJUAL TERPILIH SHOPEE</p>
            </div>
            <div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:27.5974%;left:18.9436%;width:26.1372%;margin-left:-13.0686%;'>
                <p class='g-aiPstyle2'>Detil No. KTP telah sukses diterima dan disetujui oleh Shopee</p>
            </div>
            <div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:27.5974%;left:50%;width:26.1372%;margin-left:-13.0686%;'>
                <p class='g-aiPstyle2'>Mempunyai persentase chat dibalas: &ge;80%</p>
            </div>
            <div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:27.5974%;left:81.0564%;width:26.1372%;margin-left:-13.0686%;'>
                <p class='g-aiPstyle2'>Mempunyai rating: &ge;4.5</p>
            </div>
            <div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:35.3504%;left:21.373%;'>
                <p class='g-aiPstyle3'>TOTAL ORDER:</p>
            </div>
            <div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:36.386%;left:18.9436%;width:26.8323%;margin-left:-13.4161%;'>
                <p class='g-aiPstyle2'>Mempunyai</p>
                <p class='g-aiPstyle2'>minimum jumlah transaksi berhasil sebesar 50 pesanan dalam sebulan terakhir</p>
            </div>
            <div id='g-ai0-10' class='g-Layer_1 g-aiAbs' style='top:36.386%;left:50%;width:26.1372%;margin-left:-13.0686%;'>
                <p class='g-aiPstyle2'>Melayani</p>
                <p class='g-aiPstyle4'>25 pembeli berbeda dalam </p>
                <p class='g-aiPstyle2'>sebulan terakhir</p>
            </div>
            <div id='g-ai0-11' class='g-Layer_1 g-aiAbs' style='top:36.386%;left:81.0564%;width:27.1838%;margin-left:-13.5919%;'>
                <p class='g-aiPstyle2'>Pembatalan dan pengembalian dalam sebulan </p>
                <p class='g-aiPstyle2'>terakhir <10%</p>
            </div>
            <div id='g-ai0-12' class='g-Layer_1 g-aiAbs' style='top:44.083%;left:50%;width:87.5%;margin-left:-43.75%;'>
                <p class='g-aiPstyle2'>Pastikan bahwa produk yang kamu jual sesuai dengan Ketentuan dan Kebijakan Shopee</p>
            </div>
            <div id='g-ai0-13' class='g-Layer_1 g-aiAbs' style='top:47.1898%;left:48.6712%;width:76.5344%;margin-left:-38.2672%;'>
                <p class='g-aiPstyle5'>CEK KRITERIA LENGKAP DI SINI</p>
            </div>
            <div id='g-ai0-14' class='g-Layer_1 g-aiAbs' style='top:50.2407%;left:50%;width:98.6987%;margin-left:-49.3494%;'>
                <p class='g-aiPstyle1'>BAGAIMANA CARA MENGENALI</p>
                <p class='g-aiPstyle1'>PENJUAL TERPILIH SHOPEE?</p>
            </div>
            <div id='g-ai0-15' class='g-Layer_1 g-aiAbs' style='top:52.9836%;left:50%;width:87.5%;margin-left:-43.75%;'>
                <p class='g-aiPstyle2'>Penjual Terpilih Shopee dapat dikenali dari</p>
                <p class='g-aiPstyle2'>badge               yang dapat kamu temukan di:</p>
            </div>
            <div id='g-ai0-16' class='g-Layer_1 g-aiAbs' style='top:53.9912%;left:32.7062%;width:13.4043%;margin-left:-6.7021%;'>
                <p class='g-aiPstyle6'>Terpilih</p>
            </div>
            <div id='g-ai0-17' class='g-Layer_1 g-aiAbs' style='top:58.8893%;left:10.3936%;width:4.22%;margin-left:-2.11%;'>
                <p class='g-aiPstyle7'>Terpilih</p>
            </div>
            <div id='g-ai0-18' class='g-Layer_1 g-aiAbs' style='top:60.6527%;left:11.7487%;width:13.4329%;margin-left:-6.7164%;'>
                <p class='g-aiPstyle6'>Terpilih</p>
            </div>
            <div id='g-ai0-19' class='g-Layer_1 g-aiAbs' style='top:60.7926%;left:74.4273%;width:13.4329%;margin-left:-6.7164%;'>
                <p class='g-aiPstyle6'>Terpilih</p>
            </div>
            <div id='g-ai0-20' class='g-Layer_1 g-aiAbs' style='top:62.6679%;left:59.0822%;width:13.4329%;margin-left:-6.7164%;'>
                <p class='g-aiPstyle6'>Terpilih</p>
            </div>
            <div id='g-ai0-21' class='g-Layer_1 g-aiAbs' style='top:68.1258%;left:18.9436%;width:26.1372%;margin-left:-13.0686%;'>
                <p class='g-aiPstyle2'>Bawah foto profil toko</p>
            </div>
            <div id='g-ai0-22' class='g-Layer_1 g-aiAbs' style='top:68.1258%;left:50%;width:26.1372%;margin-left:-13.0686%;'>
                <p class='g-aiPstyle2'>Setiap halaman</p>
                <p class='g-aiPstyle2'>produk</p>
            </div>
            <div id='g-ai0-23' class='g-Layer_1 g-aiAbs' style='top:68.1258%;left:81.0564%;width:26.1372%;margin-left:-13.0686%;'>
                <p class='g-aiPstyle2'>Setiap foto produk</p>
            </div>
            <div id='g-ai0-24' class='g-Layer_1 g-aiAbs g-aiPtransformed' style='left:32.0338%;top:72.4689%;transform: matrix(0,-1,1,0,0,0) scaleX(1) scaleY(1);transform-origin: left top;-webkit-transform: matrix(0,-1,1,0,0,0) scaleX(1) scaleY(1);-webkit-transform-origin: left top;-ms-transform: matrix(0,-1,1,0,0,0) scaleX(1) scaleY(1);-ms-transform-origin: left top;'>
                <p class='g-aiPstyle8'>213.473 px</p>
            </div>
            <div id='g-ai0-25' class='g-Layer_1 g-aiAbs' style='top:71.9323%;left:49.9999%;width:89.9539%;margin-left:-44.9769%;'>
                <p class='g-aiPstyle1'>APA KEUNTUNGAN MENJADI</p>
                <p class='g-aiPstyle1'>PENJUAL TERPILIH SHOPEE?</p>
            </div>
            <div id='g-ai0-26' class='g-Layer_1 g-aiAbs' style='top:75.347%;left:20.8726%;width:11.093%;margin-left:-5.5465%;'>
                <p class='g-aiPstyle9'>Terpilih</p>
            </div>
            <div id='g-ai0-27' class='g-Layer_1 g-aiAbs g-aiPtransformed' style='left:56.3447%;top:76.9393%;transform: matrix(0.9647,-0.2632,0.1264,0.992,-22.2534,0) scaleX(0.9903) scaleY(1);transform-origin: center top;-webkit-transform: matrix(0.9647,-0.2632,0.1264,0.992,-22.2534,0) scaleX(0.9903) scaleY(1);-webkit-transform-origin: center top;-ms-transform: matrix(0.9647,-0.2632,0.1264,0.992,-22.2534,0) scaleX(0.9903) scaleY(1);-ms-transform-origin: center top;'>
                <p class='g-aiPstyle10'>SALE!</p>
            </div>
            <div id='g-ai0-28' class='g-Layer_1 g-aiAbs' style='top:79.6014%;left:19.7769%;width:27.8038%;margin-left:-13.9019%;'>
                <p class='g-aiPstyle11'>Toko Lebih Menarik dengan Tampilan Eksklusif</p>
                <p class='g-aiPstyle12'>Tokomu akan terlihat lebih terpercaya dan istimewa dibandingkan toko yang lain dengan badge kami.</p>
            </div>
            <div id='g-ai0-29' class='g-Layer_1 g-aiAbs' style='top:79.6014%;left:50%;width:25.3228%;margin-left:-12.6614%;'>
                <p class='g-aiPstyle11'>Kesempatan</p>
                <p class='g-aiPstyle11'>Bergabung Dalam Promosi</p>
                <p class='g-aiPstyle12'>Mendapatkan lebih banyak exposure dan dapat menjangkau lebih banyak pembeli.</p>
            </div>
            <div id='g-ai0-30' class='g-Layer_1 g-aiAbs' style='top:79.6014%;left:81.4637%;width:25.3226%;margin-left:-12.6613%;'>
                <p class='g-aiPstyle11'>Koin Shopee Eksklusif untuk Penjual Terpilih Shopee</p>
                <p class='g-aiPstyle12'>Koin Shopee tidak dapat digunakan pada penjual lainnya.</p>
            </div>
            <div id='g-ai0-31' class='g-Layer_1 g-aiAbs' style='top:88.8378%;left:80.3977%;width:38.7603%;margin-left:-19.3801%;'>
                <p class='g-aiPstyle5'>SELENGKAPNYA</p>
            </div>
            <div id='g-ai0-32' class='g-Layer_1 g-aiAbs' style='top:94.2677%;left:54.4183%;width:70.873%;margin-left:-35.4365%;'>
                <p class='g-aiPstyle13'>GABUNG SEKARANG</p>
            </div>
            <div id='g-ai0-33' class='g-Layer_1 g-aiAbs' style='top:97.0107%;left:50%;width:87.5%;margin-left:-43.75%;'>
                <p class='g-aiPstyle2'>Pendaftaran dan pengumuman Penjual Terpilih Shopee akan dilakukan setiap hari Jumat.</p>
            </div>
        </div>
    </div>

    <!-- Artboard: Artboard_1_copy_3 -->
    <div id='g-Index-Page-Design-Artboard_1_copy_3' class='g-artboard g-artboard-v3 ' data-min-width='800'>
        <style type='text/css' media='screen,print'>
            #g-Index-Page-Design-Artboard_1_copy_3{
                position:relative;
                overflow:hidden;
                width:800px;
            }
            .g-aiAbs{
                position:absolute;
            }
            .g-aiImg{
                display:block;
                width:100% !important;
            }
            #g-Index-Page-Design-Artboard_1_copy_3 p{
                font-family:nyt-franklin,arial,helvetica,sans-serif;
                font-size:13px;
                line-height:18px;
                margin:0;
            }
            .g-aiPtransformed p { white-space: nowrap; }
        </style>
        <div id='g-Index-Page-Design-Artboard_1_copy_3-graphic'>
            <img id='g-ai1-0'
                 class='g-aiImg'
                 src='Index-Page-Design-Artboard_1_copy_3.png'
                 />
        </div>
    </div>


    <!-- End ai2html - 2017-06-21 - 22:16 -->
</div>
